# Generated by Django 2.2.4 on 2019-08-14 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_done', models.DateTimeField(verbose_name='date sent')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.TextField(default='radio'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Response')),
            ],
        ),
    ]
