# Generated by Django 2.2.4 on 2019-08-16 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20190815_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.Page'),
        ),
    ]
